### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jpfairbanks** [rohitvarkey/GraphChallenge.jl#8]
Here is the roadmap for the semester

- [x] PGSQL implementation
- [ ] Benchmark and profiling system
- [ ] Pick challenge conforming output formats
- [ ] Updating the graph leveraging old clusters
- [ ] Parallel implementation
- [ ] Paper Submission

**Comment by jpfairbanks** [comment]
- [ ] find a place to run pgsql on fast hardware.
